### ISSUE TITLE
Crash occurring when authenticating user for Game Center

### ISSUE THREAD

**Issue by FunkyFingerJames** [apple/unityplugins#60]
**Describe the bug**
I am using the latest version of the Game Center plugin for Unity and have noticed that my game will crash on launch when trying to authenticate.

I've tried this in an empty project with just the plugin and it still crashes with this exception.
`	GfxDevice: creating device client; threaded=1; jobified=0
	Initializing Metal device caps: Apple A14 GPU
	Initialize engine version: 2022.3.62f2 (7670c08855a9)
	GameKitException: Code=-7 Domain=GKErrorDomain Description=The operation couldn’t be completed. (GKErrorDomain error -7.) (UnsupportedOperationForOSVersion)
	  at Apple.GameKit.DefaultNSErrorHandler.ThrowNSError (System.IntPtr nsErrorPtr) [0x00000] in <00000000000000000000000000000000>:0 
	Rethrow as TypeInitializationException: The type initializer for 'Apple.GameKit.GKGameActivity' threw an exception.`

And the area in the native code that is triggering the crash is this inside the GKLocalPlayer_SetAuthenticateHandler function
`_onAuthenticate!(tid, _mostRecentAuthenticatePlayer!.passRetainedUnsafeMutablePointer());`

I have also included this message because I thought it might help too

`terminating due to uncaught exception of type Il2CppExceptionWrapper Could not import Swift modules for translation unit: failed to get module "GameKitWrapper" from AST context: error: 'GKErrorCodeExtension.h' file not found in file included from <module-includes>:1: error: could not build Objective-C module 'GameKitWrapper' warning: Ignoring missing VFS file: /Users/james/Library/Developer/Xcode/DerivedData/GameKitWrapper-dzawbtxqdxdviiakfxmfunexppqv/Build/Intermediates.noindex/GameKitWrapper.build/Release-iphoneos/GameKitWrapper-bc72bd3638f4d2956cac9b00e84c1a7d-VFS-iphoneos/all-product-headers.yaml This is the likely root cause for any subsequent compiler errors.warning: Ignoring missing VFS file: /Users/bill/Library/Developer/Xcode/DerivedData/GameKitWrapper-dzawbtxqdxdviiakfxmfunexppqv/Build/Intermediates.noindex/GameKitWrapper.build/Release-iphoneos/GameKitWrapper iOS.build/unextended-module-overlay.yaml This is the likely root cause for any subsequent compiler errors.warning: TypeSystemSwiftTypeRef::GetNumChildren: had to engage SwiftASTContext fallback for type $syyXCD`

**To Reproduce**
Create XCode build and run on iOS device.
The error occurs when the GKLocalPlayer.Authenticate() function is called.
I have also included the script that we use for triggering the function (see attached GameCenterManager script).

We can update our Mac Mini to macOS 26 if need be but we would like to know ahead of time how likely it is that this would fix this issue as the min specs for this plugin state that it should support macOS 11.5 and iOS 15.6. We are not actually using GKGameActivity as you can see in the attached GameCenterManager script. We are only trying to add achievement support.

- Device: Mac Mini M2 2023, iPhone 12 mini
 - OS: MacOS 15.7.2, iOS 18.6.2
 - Version: Unity 2022.3.62f2
 - Plugin Components: Core, GameKit

[GameCenterManager.txt](https://github.com/user-attachments/files/23489746/GameCenterManager.txt)

**Comment by sebastienmalicet** [comment]
Hello,
"Apple.GameKit.GKGameActivity" feature required macOS 26.

**Comment by FunkyFingerJames** [comment]
Ok, so if we update to macOS 26 then it should fix this issue on the iOS build? Why does the main repo page mention the minimum supported version of macOS is 11.5 if using GameKit will require updating to macOS 26? is it just out of date because of the recent commit that added support for 26?

We aren't actually using Game Activity, our code right now is only trying to authenticate at the moment.

**Comment by boena** [comment]
I'm having the same issues here running Unity 6000.2.13f1 and Xcode 26.1.1. I've tried downgrading to 3.0.2 release but still face the same issues. Trying it on my iPhone with iOS 26.0.1 :(

**Comment by KevinBjorv** [comment]
> I can also confirm what [@FunkyFingerJames](https://github.com/FunkyFingerJames) said that setting Managed Stripping Level to Minimal actually fixes the crash and my user is correctly signed in on both 3.0.2 and 4.0.1...

Doesn't work for me unfortunently. I had to disable gamekit for all users not on IOS 26. That's the only solution I could find.

**Comment by JVimes** [comment]
@ryzngard My bad. 4.0.1 works on my machine.
